###CREATE NEW TASK
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title" : "Learn JWT",
    "description" : "ASAP"
}

###GET ALL TASKS
GET http://localhost:3000/tasks

###GET TASK BY ID
GET http://localhost:3000/tasks/655486d9d569333a0be4d452
