###CREATE NEW TASK
POST http://localhost:3000/api/tasks/new-task
Content-Type: application/json

{
    "title" : "Learn MVC",
    "description" : "ASAP"
}

###GET ALL TASKS
GET http://localhost:3000/api/tasks/get-all-tasks

###GET TASK BY ID
GET http://localhost:3000/api/tasks/get-task/6554adff9275327bfb3e46ba

###QUICK TASK UPDATE
PATCH http://localhost:3000/api/tasks/quick-update-task/6554adff9275327bfb3e46ba
Content-Type: application/json

{
    "title": "Updated only Task Title"
}