###CREATE NEW TASK
POST http://localhost:3000/api/tasks/new-task
Content-Type: application/json

{
    "title" : "Learn auth methods",
    "description" : "ASAP"
}

###GET ALL TASKS
GET http://localhost:3000/api/tasks/get-all-tasks

###GET TASK BY ID
GET http://localhost:3000/api/tasks/get-task/6554adff9275327bfb3e46ba

###QUICK TASK UPDATE
PATCH http://localhost:3000/api/tasks/quick-update-task/6554c4591f408228f10deaa6
Content-Type: application/json

{
    "title": "Learn NestJs",
    "description": "ASAP"
}

###UPDATE SET ASIGNEE ID TO TASK
PATCH http://localhost:3000/api/tasks/update-task-with-assignee/6555d243a8b87d50e69d5926
Content-Type: application/json

{
    "title": "Updated Task Title",
    "description": "Smth new",
    "assignee": "6554838ee961c23e4612afa8"
}

###ASIGN TASK TO PARTICULAR USER
PATCH http://localhost:3000/api/tasks/assign-task/6555d243a8b87d50e69d5926
Content-Type: application/json

{
    "userId": "6554ac5c34fcf559a0e40b05"
}

###GET ALL TASKS FOR SPECIFIC USER
GET http://localhost:3000/api/tasks/get-user-tasks/6554ac5c34fcf559a0e40b05