###CREATE NEW USER
POST http://localhost:3000/api/users/new-user
Content-Type: application/json

{
    "name" : "Mihai",
    "email" : "bgtmih@yahoo.com",
    "password" : "mihaisefu",
    "age" : 25
}

###GET ALL USERS
GET http://localhost:3000/api/users/get-all-users

###GET USER BY ID
GET http://localhost:3000/api/users/get-user/6554834ce961c23e4612afa4

###UPDATE USER
PATCH http://localhost:3000/api/users/update-user/6554838ee961c23e4612afa8
Content-Type: application/json

{
    "name": "Updated Name",
    "age": 26
}

###DELETE USER
DELETE http://localhost:3000/api/users/delete-user/6554989b33e327c577e3aae6