# ###CREATE NEW USER
# POST http://localhost:3000/api/users/new-user
# Content-Type: application/json

# {
#     "name" : "Mihai",
#     "email" : "bgtmih@yahoo.com",
#     "password" : "mihaisefu",
#     "age" : 25
# }

###GET ALL USERS
GET http://localhost:3000/api/users/get-all-users

###GET USER BY ID
GET http://localhost:3000/api/users/get-user/655b1f6de9ce900f93f73bc7

###UPDATE USER
PATCH http://localhost:3000/api/users/update-user/6554838ee961c23e4612afa8
Content-Type: application/json

{
    "name": "Updated Name",
    "age": 26
}

###DELETE USER
DELETE http://localhost:3000/api/users/delete-user/6554989b33e327c577e3aae6

###LOGIN - ADMIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "gabe99@yahoo.com",
    "password": "gabe070199"
}

###LOGIN - NORMAL USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "bgtmih@yahoo.com",
    "password": "mihaisefu"
}

###REGISTER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Mihai",
    "email": "bgtmih@yahoo.com",
    "password": "mihaisefu",
    "age": 30
}

###
PATCH http://localhost:3000/api/users/set-user-role/655b1f6de9ce900f93f73bc7
Content-Type: application/json

{
    "role": "admin"
}

###PROTECTED ROUTES
GET http://localhost:3000/auth/protected
Headers:
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3NTQ3N2M5MDlhYTE1OGMyYjcwZTIiLCJpYXQiOjE3MDA0NjU1NjUsImV4cCI6MTcwMDQ2OTE2NX0.rNo1F0ThEjTtGER7wDi4hxscZY6cGNk6zTv6cqcZwi8
